### ISSUE TITLE
RIPE notice on STDOUT that shouldn't go to STDOUT?

### ISSUE THREAD

**Issue by robert-scheck** [kristapsdz/rpki-client#4]
Is it really intended that the RIPE notice ends up on STDOUT? I thought comments in OpenBGPD should start using a hash mark…

```
# rpki-client -e rsync tals/*.tal > vrp.filter
rpki-client:  ...trace: error:02001002:system library:fopen:No such file or directory
rpki-client:  ...trace: error:2006D080:BIO routines:BIO_new_file:no such file
rpki-client: /var/cache/rpki-client/ca.rg.net/rpki/RGnet/WWz_C2qLO_yVk8-8glRCLHuz7Fw.mft: BIO_new_file
rpki-client:  ...trace: error:02001002:system library:fopen:No such file or directory
rpki-client:  ...trace: error:2006D080:BIO routines:BIO_new_file:no such file
rpki-client: /var/cache/rpki-client/ca.rg.net/rpki/RGnet-OU/ovsCA/aaI5ikDRYL7nJH9kwrv4b80iIAI.mft: BIO_new_file
# 
```

```
# head vrp.filter
The RIPE NCC Certification Repository is subject to Terms and Conditions
See http://www.ripe.net/lir-services/ncc/legal/certification/repository-tc

The RIPE NCC Certification Repository is subject to Terms and Conditions
See http://www.ripe.net/lir-services/ncc/legal/certification/repository-tc

roa-set {
    1.0.0.0/24 source-as 13335
    1.1.1.0/24 source-as 13335
    1.160.0.0/12 maxlen 24 source-as 3462
# 
```

**Comment by job** [comment]
This doesn’t happen with openrsync, but indeed needs to be addressed when
the common rsync is used.

**Comment by cjeker** [comment]
This was fixed in openrsync some time ago (should now behave like rsync).
The MOTD in rsyncd should only be printed if -v was passed to rsync.

**Comment by robert-scheck** [comment]
As per 0.3.0 the RIPE notice still exists (without passing `-v` to `rsync` or to `rpki-client`).

**Comment by robert-scheck** [comment]
It gets silent once I pass `--no-motd` to Samba rsync. This however would require a code change like (a conditional) `args[i++] = "--no-motd";` at [main.c:719](https://github.com/kristapsdz/rpki-client/blob/master/main.c#L719), because `openrsync` doesn't seem to have this option. Any upstream opinions on this?
